export const AUTH_MESSAGES = {
    LOGIN_SUCCESS: 'Login successful!',
    LOGIN_FAILED: 'Login failed. Please check your credentials and try again.',
    LOGOUT_SUCCESS: 'Logged out successfully.',
    LOGOUT_FAILED: 'Failed to log out. Please try again later.',
    SIGNUP_SUCCESS: 'Sign-up successful! Welcome aboard.',
    SIGNUP_FAILED: 'Sign-up failed. Please check your information and try again.',
    PASSWORD_RESET_REQUEST: 'Password reset request sent successfully.',
    PASSWORD_RESET_FAILED: 'Failed to send password reset request. Please try again later.',
    PASSWORD_CHANGED: 'Password changed successfully.',
    PASSWORD_CHANGE_FAILED: 'Failed to change password. Please try again later.',
    INVALID_LOGIN_DATA: 'Invalid login data. Please check your credentials.',
    ACCOUNT_LOCKED: 'Your account is locked. Please contact support.',
    ACCOUNT_NOT_FOUND: 'Account not found. Please sign up first.',
    ACCOUNT_ALREADY_EXISTS: 'An account with this email already exists.',
    AUTH_LOADING: 'Processing authentication...',
    API_ERROR: 'Invalid Action or method not allowed.',
    UNAUTHORIZED: 'Unauthorized access. Please log in to continue.',
  };
  