export const CRM_MESSAGES = {
    LEAD_RECEIVED: 'New lead received successfully!',
    FAILED_TO_RECEIVE_LEAD: 'Failed to receive lead. Please try again later.',
    LEAD_PROCESSED: 'Lead data has been processed.',
    INVALID_LEAD_DATA: 'Invalid lead data received. Please check the webhook payload.',
    LOADING_LEAD: 'Loading lead data...',
    LEAD_ALREADY_EXISTS: 'This lead already exists in the system.',
    LEAD_ADDED_SUCCESS: 'Lead added successfully!',
    LEAD_ADD_FAILED: 'Failed to add lead. Please try again.',
    LEAD_UPDATED_SUCCESS: 'Lead updated successfully!',
    LEAD_UPDATE_FAILED: 'Failed to update lead. Please try again.',
    LEAD_DELETED_SUCCESS: 'Lead deleted successfully!',
    LEAD_DELETION_FAILED: 'Failed to delete lead. Please try again.',
    OPPORTUNITY_CREATED: 'New opportunity created successfully!',
    OPPORTUNITY_CREATION_FAILED: 'Failed to create opportunity. Please try again.',
    OPPORTUNITY_UPDATED: 'Opportunity updated successfully!',
    OPPORTUNITY_UPDATE_FAILED: 'Failed to update opportunity. Please try again.',
    OPPORTUNITY_DELETED: 'Opportunity deleted successfully!',
    OPPORTUNITY_DELETION_FAILED: 'Failed to delete opportunity. Please try again.',
    DEAL_CREATED: 'Deal created successfully!',
    DEAL_CREATION_FAILED: 'Failed to create deal. Please try again.',
    DEAL_UPDATED: 'Deal updated successfully!',
    DEAL_UPDATE_FAILED: 'Failed to update deal. Please try again.',
    DEAL_DELETED: 'Deal deleted successfully!',
    DEAL_DELETION_FAILED: 'Failed to delete deal. Please try again.',
    TASK_CREATED: 'Task created successfully!',
    TASK_CREATION_FAILED: 'Failed to create task. Please try again.',
    TASK_UPDATED: 'Task updated successfully!',
    TASK_UPDATE_FAILED: 'Failed to update task. Please try again.',
    TASK_DELETED: 'Task deleted successfully!',
    TASK_DELETION_FAILED: 'Failed to delete task. Please try again.',
    FOLLOW_UP_SCHEDULED: 'Follow-up scheduled successfully!',
    FOLLOW_UP_SCHEDULING_FAILED: 'Failed to schedule follow-up. Please try again.',
    EMAIL_SENT: 'Email sent successfully!',
    EMAIL_SEND_FAILED: 'Failed to send email. Please try again.',
    INVALID_INPUT: 'Invalid input. Please check and try again.',
    ACTION_SUCCESS: 'Action completed successfully!',
    ACTION_FAILED: 'Action failed. Please try again.',
    RECORD_NOT_FOUND: 'Record not found.',
    AUTH_REQUIRED: 'Authentication required. Please log in.',
    LOADING_DATA: 'Loading data...',
    DATA_SAVED: 'Data saved successfully!',
    DATA_SAVE_FAILED: 'Failed to save data. Please try again.',
    SYSTEM_ERROR: 'A system error occurred. Please contact support.',
    CONNECTION_ERROR: 'Connection error. Please check your internet connection.',
    PROFILE_UPDATED: 'Profile updated successfully!',
    LEAD_UPDATED_ERROR : 'Unable To Update Lead!',
};