name: Weekly K6 Load Test

on:
  schedule:
    - cron: "0 3 * * 1"  
  workflow_dispatch:      

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Install K6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.52.0/k6-v0.52.0-linux-amd64.tar.gz | tar xz
          sudo mv k6-v0.52.0-linux-amd64/k6 /usr/local/bin/

      - name: Create Results Directory
        run: mkdir -p k6-results

      - name: Run K6 Load Test
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        run: |
          k6 run load-tests/script.js \
            --out json=k6-results/raw.json \
            --summary-export=k6-results/summary.json

      - name: Generate Weekly Report
        if: always()
        run: |
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Weekly K6 Load Test Results</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 20px; }
              pre { background: #f5f5f5; padding: 15px; border-radius: 5px; }
            </style>
          </head>
          <body>
            <h1>Weekly K6 Load Test Results</h1>
            <h2>Test Run: $(date)</h2>
            <pre>$(cat k6-results/summary.json)</pre>
          </body>
          </html>" > k6-results/weekly-report.html

      - name: Upload K6 Results
        if: always()
        uses: actions/upload-artifact@v4  
        with:
          name: k6-weekly-results
          path: k6-results/
          retention-days: 90

      - name: Check Test Status
        if: always()
        run: |
          if grep -q '"failed":true' k6-results/summary.json; then
            echo "Weekly load test failed - Check results for details"
            exit 1
          fi